### PR TITLE
Fix/role bot2

### PR DESCRIPTION
**Pull request by HeinrichOlfert**
#16 fix code.

### CODE REVIEW

**Review by chrlschwb — APPROVED** [review]
The new code has totally removed "/claim" and "/solve" and relies on QN data to map Joystream memberships to discord handles.
Works well.

**Comment by DzhideX** [comment]
Okay, after another quick review, a lot of it has been implemented but not all of it (to the extent that I'd like it to).

Namely, the following still need work:
  - who_is:
    - if no mapping for user: reply explaining that and link to a external resource to establish it (missing external resource)

  - list_role_members:
    - my interpretation of this is that it should go through all the members with this role and display "who_is data" for all of them
    - "list_role_members" (based on the spec) shouldn't necessarily list all discord roles, just the relevant (on-chain) ones


That being said, since these are all related to the new messages being written by HR Lead Mariia I think it'd be acceptable to consider this done (functionality-wise) ✅

**Comment by chrlschwb** [comment]
> Okay, after another quick review, a lot of it has been implemented but not all of it (to the extent that I'd like it to).
> 
> Namely, the following still need work:
> 
> * who_is:
>   
>   * if no mapping for user: reply explaining that and link to a external resource to establish it (missing external resource)
> * list_role_members:
>   
>   * my interpretation of this is that it should go through all the members with this role and display "who_is data" for all of them
>   * "list_role_members" (based on the spec) shouldn't necessarily list all discord roles, just the relevant (on-chain) ones
> 
> That being said, since these are all related to the new messages being written by HR Lead Mariia I think it'd be acceptable to consider this done (functionality-wise) ✅

I think "list_role_members" should not display all the "who_is data" for all members. That would be repetition.

**Comment by DzhideX** [comment]
Here's what is written in the original spec for that specific point:

> same as doing who_is on all discord handles in discord role, and include discord handles that hve no mapping, just as in who_is.

I disagree that it would be repetition. The reasoning is that you're saying give me all the roles of these specific members. So, you want more information than just who the members are who hold that one role. I don't see how it's repetition, it's just a different way to do it and if you have problems with it, then you have problems with the spec and you should raise that with Bedeho as I can't make any executive decision on that front.

**Comment by bedeho** [comment]
I strongly recommend Gitflow branch management is used from now on, not merging from some remote fork directly into main.

**Pull request merged**
