### PR TITLE
Fix/role bot

### PR DESCRIPTION
**Pull request by HeinrichOlfert**
This is the role bot described here.
https://github.com/Joystream/discord-bot/issues/5

### CODE REVIEW

**Comment by chrlschwb** [comment]
The creator role needs to be added. The video count must be retrieved from Orion.

**Review by chrlschwb — APPROVED** [review]
All good except the "creator" role which should be added after Orion endpoint becomes accessible to the bot

**Comment by DzhideX** [comment]
A massive task, it couldn't have been easy to implement this, big props to Mr. @HeinrichOlfert. Also, it seems the parts with address inputs are much more robust so great work on that as well 👍 

I just finished testing the bot and I have some general thoughts on what could be fixed for now:
- Maybe increase limit of fetched members in getMembers query.
- Current block calculation is incorrect, for me it showed a value larger than current block (I think an approximation is not appropriate for this).
- (control.ts) Can we re-write all of the switch cases into something more modular/easier to read. Later down the line it is going to be easier to change as well, currently it's hard to keep track of all of it.
- (control.ts) Let's remove the usage of "any" in this file if possible.
- Claim wallet should not only catch the error but let the user know the address they tried to use was invalid
- Although I don't expect anyone to try to break this anytime soon, I think it makes sense to update generateKeyFromSeed to use something more cryptographically secure than Math.random to generate the challenge key
- Missing status indicator in /status.
- It seems that when we have an account that doesn't have any roles we respond with: "There is not already register and verify.". We should mention that the user doesn't possess any roles rather imo.
- In general, can we revisit all of the messages both from a content but also grammatical POV. Sometimes it's not obvious what is going on and what should happen.
- Let's add some more input validation on the commands wherever possible (e.g., who_is, list_role_members)

**Comment by mochet** [comment]
Great work so far!
Please see this: https://github.com/Joystream/discord-bot/issues/16

I think this should be adjusted to ask for the membership handle rather than root address for multiple reasons explained in the issue.

**Comment by bedeho** [comment]
No longer relevant, recent work is here https://github.com/Joystream/discord-bot/pull/17

**Pull request closed without merging**
